---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "04:00"
    assignees:
      - "kampfmoehre"
    open-pull-requests-limit: 10
  - directory: "/"
    groups:
      commitlint:
        patterns:
          - "@commitlint/*"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
    package-ecosystem: npm
    open-pull-requests-limit: 10
    schedule:
      interval: daily
      time: "04:00"
    assignees:
      - "kampfmoehre"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"
